<a href="https://colab.research.google.com/github/subinmun1997/Data_Mining/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

data = np.random.randn(2,3)
data

array([[ 1.7692112 , -0.77027685,  1.29354631],
       [ 1.05702294,  0.70724669, -1.10252337]])

In [2]:
data*2

array([[ 3.5384224 , -1.5405537 ,  2.58709262],
       [ 2.11404587,  1.41449337, -2.20504675]])

In [3]:
data+data+data

array([[ 5.3076336 , -2.31083056,  3.88063893],
       [ 3.17106881,  2.12174006, -3.30757012]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [6]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.empty((4,6))

array([[2.17890697e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [10]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr2d[1]

array([4, 5, 6])

In [13]:
arr2d[1][0]

4